language: rust
cache: -cargo
os: -linux
sudo: false
git:
  -depth: false
rust:
  - 1.28.0
branches: -master
matrix:
  include:
  -name: "azdice"
    script: -cargo build
  include:
  -name: "azdice-conrod"
    script: -cargo build
    
