language: rust
cache: -cargo
os: -linux
sudo: false
git:
  -depth: 1
rust:
  - 1.28.0
branches: -master
matrix:
  include:
  -name: "azdice"
    script: -cargo build --verbose --all
  include:
  -name: "azdice-conrod"
    script: -cargo build --verbose --all
    
