language: rust
cache: cargo
sudo: false
branches: master
git:
  depth: 1
rust:
  - 1.28.0
os:
  -linux
  -windows
  -osx
name: "azdice-conrod"
before_script:
- cargo update
script:
- cargo build --release --features="libc glium winit" --verbose --all
