language: rust
cache: cargo
sudo: true
branches: master
os:
  -linux
  -windows
  -osx
git:
  depth: 1
rust:
  - 1.43.0
name: "azdice-conrod"
before_script:
- cargo update
script:
- cargo build --release --verbose --all
