
addons:
  apt:
    packages:
    - libxcb-shape0
    - libxcb-xfixes0
    - libxcb-shape0-dev
    - libxcb-xfixes0-dev
    
language: rust
cache: cargo
sudo: true
branches: master
os:
  -linux
  -windows
  -osx
git:
  depth: 1
rust:
  - 1.43.0
name: "azdice-conrod"
before_script:
# - sudo apt install libxcb-shape0
# - sudo apt install libxcb-xfixes0
# - sudo ldconfig
# - sudo apt install libxcb-shape0-dev
# - sudo apt install libxcb-xfixes0-dev
- cargo update
script:
- cargo build --release
