[package]
name = "azdice"
version = "0.1.0"
authors = ["Aleksey Zholobenko <aleshaleksey@googlemail.com>"]

[dependencies]
rand="=0.3.16"

[profile.release]
opt-level = 3
debug = false
rpath = false
lto =true
debug-assertions = false
codegen-units = 1
panic = 'unwind'
